name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{secrets.EC2_SSH_KEY}}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-110-221-28.ap-south-1.compute.amazonaws.com << 'EOF'
          cd /home/ec2-user/mem0-rest
          git pull origin main
          /usr/local/bin/docker-compose up --build -d
        EOF
